-- Migration Phase 5: Telegram Bot Message Logging
-- Creates table to log incoming and outgoing Telegram Bot messages and configures RLS.

CREATE TABLE IF NOT EXISTS public.telegram_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    sender_id BIGINT,
    username TEXT,
    first_name TEXT,
    last_name TEXT,
    message_text TEXT,
    is_from_bot BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.telegram_messages ENABLE ROW LEVEL SECURITY;

-- Policy to allow inserts from anyone (necessary for the Telegram webhook)
CREATE POLICY "Allow public inserts" 
ON public.telegram_messages 
FOR INSERT 
WITH CHECK (true);

-- Policy to allow reads only for administrators
CREATE POLICY "Allow admin read access" 
ON public.telegram_messages 
FOR SELECT 
USING (
    EXISTS (
        SELECT 1 
        FROM public.profiles 
        WHERE id = auth.uid() 
          AND is_admin = true
    )
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_telegram_messages_chat_id ON public.telegram_messages(chat_id);
CREATE INDEX IF NOT EXISTS idx_telegram_messages_created_at ON public.telegram_messages(created_at);
